---
title: "RachelReporting"
author: "Pri"
date: "24/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

 
    library(tidyverse)
    library(magrittr)
    library(readxl)
    library(httr)
    library(stringr)
    #because readxl cant read in from url yet
    GET(url="https://www.euclids-perform-diamonds-h2020.eu/media/DIAMONDS_DAILY_EXPORT.xlsx",
        write_disk(tf <- tempfile(fileext = ".xlsx")))
    diamonds <- read_xlsx(tf)
    
    remove0 <- function(x){
        gsub("-E0","-E", x)
        
    }
    
    diamonds$UNIQUE_PATIENT_ID <- remove0(diamonds$UNIQUE_PATIENT_ID)
    diamonds$ALTERNATE_STUDY_NO <- remove0(diamonds$ALTERNATE_STUDY_NO)
    
    #### Define Limits for Abnormal Tests ####
    
    fibrinogen <- 5
    CRP <- 20
    Ddimer <- 1000
    Ferritin <- 400
    Albumin <- 25
    Lymphocytes <- 1.5
    tropT <- 14
    bnp <- 500
    PT <- 15.8
    INR <- 1.5
    PCT <- 0.15
    neutrophils <- 6
    
    aetiologyNegative <- c("NO=NULL","NO=NEGATIVE","NULL=NULL","Unk=NULL","Unk=NEGATIVE","NULL=NEGATIVE",
                           "YES=SARS-CoV-2", "NO=SARS-CoV-2", "NULL=SARS-CoV-2", "Unk=SARS-CoV-2")
    #

   
    
    #### New Functions ####
    
    positiveCovidTests <- function(`TEST_TYPE=RESULT`, ...){
        
        if(any(grepl("POSITIVE",`TEST_TYPE=RESULT`))){
            
            whichArePositive <- which(grepl("POSITIVE",str_split(`TEST_TYPE=RESULT`,";",simplify = T)))
            
            paste(gsub("=.*","",str_split(`TEST_TYPE=RESULT`,";",simplify = T)[,whichArePositive]),collapse = ";")
        } else {
            NA_character_
        }
        
    }
    
    
    negativeCovidTests <- function(`TEST_TYPE=RESULT`, ...){
        
        if(any(grepl("NEGATIVE",`TEST_TYPE=RESULT`))){
            
            whichAreNegative <- which(grepl("NEGATIVE",str_split(`TEST_TYPE=RESULT`,";",simplify = T)))
            
            paste(gsub("=.*","",str_split(`TEST_TYPE=RESULT`,";",simplify = T)[,whichAreNegative]),collapse = ";")
        } else {
            NA_character_
        }
        
    }
    
    
    feverLength <- function(DATE_FEVER_ONSET,
                            DATE_FIRST_HOSPITAL,
                            DATETIME_FRB, 
                            FEVER,
                            ...){
        if(is.na(DATE_FEVER_ONSET)){
            if(!FEVER %in% "YES"){
                NA_integer_
            } else{100}
        } else if(!is.na(DATETIME_FRB)) {
            as.integer(as.Date(DATETIME_FRB) - as.Date(DATE_FEVER_ONSET))
        } else if(!is.na(DATE_FIRST_HOSPITAL)){
            as.integer(as.Date(DATE_FIRST_HOSPITAL) - as.Date(DATE_FEVER_ONSET))
        } else {100}
    }
    
    misCFeatures <- function(RASH,
                             CONJUNCTIVITIS,
                             INFLAMMED_EXTREMITIES,
                             MUCOSITIS,
                             SHOCK,
                             `TIME_POINT_12=INOTROPES`,
                             INOTROPES,
                             FIRST_ECHO_NORMAL,
                             FIRST_MYOCARDITIS,
                             FIRST_PERICARDITIS,
                             FIRST_VALVULAR_REGURGITATION,
                             WORST_ECHO_NORMAL,
                             WORST_MYOCARDITIS,
                             WORST_PERICARDITIS,
                             WORST_VALVULAR_REGURGITATION,
                             `TIME_POINT_19=TROP_T`,
                             `TIME_POINT_22=BNP_NT`,
                             `TIME_POINT_21=INR`,
                             `TIME_POINT_9=PT`,
                             GASTROINTESTINAL,
                             ...){
        
        score <- 0
        
        if ("YES" %in% c(RASH,CONJUNCTIVITIS,MUCOSITIS,INFLAMMED_EXTREMITIES)) {score <- score + 1}
        
        if ("YES" %in% c(SHOCK,INOTROPES) | grepl("YES",`TIME_POINT_12=INOTROPES`)) {score <- score + 1}
        
        if (
            "NO" %in% c(FIRST_ECHO_NORMAL,WORST_ECHO_NORMAL) |
            "YES" %in% c(FIRST_MYOCARDITIS,FIRST_PERICARDITIS,FIRST_VALVULAR_REGURGITATION,
                         WORST_MYOCARDITIS,WORST_PERICARDITIS,WORST_VALVULAR_REGURGITATION) |
            any(as.numeric(sub(".*=","", str_split(`TIME_POINT_19=TROP_T`,";",simplify = T)))>tropT, na.rm = T) |
            any(as.numeric(sub(".*=","",str_split(`TIME_POINT_22=BNP_NT`,";",simplify = T)))>bnp, na.rm = T)
        ) {score <- score + 1}
        
        if(
            any(as.numeric(sub(".*=","",str_split(`TIME_POINT_9=PT`,";",simplify = T)))>PT, na.rm = T) |
            any(as.numeric(sub(".*=","",str_split(`TIME_POINT_21=INR`,";",simplify = T)))>INR, na.rm = T)
        ) {score <- score + 1}
        
        if ("YES" %in% GASTROINTESTINAL) {score <- score + 1}
        
        score
    }
    
    KDcriteria <- function(RASH,
                           MUCOSITIS,
                           CONJUNCTIVITIS,
                           INFLAMMED_EXTREMITIES,
                           LYMPHADENOPATHY,
                           ...){
        score <- 0
        if(RASH %in% "YES") {score <- score + 1}
        if(MUCOSITIS %in% "YES") {score <- score + 1}
        if(CONJUNCTIVITIS %in% "YES") {score <- score + 1}
        if(INFLAMMED_EXTREMITIES %in% "YES") {score <- score + 1}
        if(LYMPHADENOPATHY %in% "YES") {score <- score + 1}
        
        score
    }
    
    maxZscore <- function(FIRST_ECHO_LOPEZ_Z_SCORE_1,
                          FIRST_ECHO_LOPEZ_Z_SCORE_2,
                          WORST_ECHO_LOPEZ_Z_SCORE_1,
                          WORST_ECHO_LOPEZ_Z_SCORE_2,
                          ...){
        
        if (all(is.na(parse_number(as.character(c(FIRST_ECHO_LOPEZ_Z_SCORE_1,
                                                  FIRST_ECHO_LOPEZ_Z_SCORE_2,
                                                  WORST_ECHO_LOPEZ_Z_SCORE_1,
                                                  WORST_ECHO_LOPEZ_Z_SCORE_2)))))){
            NA_integer_
        } else {
            
            max(parse_number(as.character(c(FIRST_ECHO_LOPEZ_Z_SCORE_1,
                                            FIRST_ECHO_LOPEZ_Z_SCORE_2,
                                            WORST_ECHO_LOPEZ_Z_SCORE_1,
                                            WORST_ECHO_LOPEZ_Z_SCORE_2))), na.rm = T)
        }
        
    }
    
    
    anyFeatures <- function(`VIRUS_DETECTED_1=VIRUS_CONSISTENT_WITH_SYMPTOMS`,
                            `VIRUS_DETECTED_2=VIRUS_ACCOUNT_ALL_FEATURES`,
                            `VIRUS_AETIOLOGY=VIRUS_DETECTED`,
                            ...) {
        
        if (grepl("SARS-CoV-2",`VIRUS_AETIOLOGY=VIRUS_DETECTED`)){
            if ("SARS-CoV-2=YES" %in% `VIRUS_DETECTED_1=VIRUS_CONSISTENT_WITH_SYMPTOMS` |
                "SARS-CoV-2=YES" %in% `VIRUS_DETECTED_2=VIRUS_ACCOUNT_ALL_FEATURES`) {TRUE
            } else if (
                "SARS-CoV-2=NO" %in% `VIRUS_DETECTED_1=VIRUS_CONSISTENT_WITH_SYMPTOMS` &
                "SARS-CoV-2=NO" %in% `VIRUS_DETECTED_2=VIRUS_ACCOUNT_ALL_FEATURES`
            ) {FALSE
            } else {NA}
            
        } else {NA}
        
        
    }
    
    otherOrgs <- function(`VIRUS_AETIOLOGY=VIRUS_DETECTED`,
                          `BACTERIA_AETIOLOGY=BACTERIA_SPECIFY`,
                          ...){
        
        if (
            all(sub(".*=","",str_split(`VIRUS_AETIOLOGY=VIRUS_DETECTED`,";",simplify = T)) %in% c(NA,NULL,"NA","NULL","SARS-CoV-2","Unk","NO"), na.rm = T) &
            all(sub(".*=","",str_split(`BACTERIA_AETIOLOGY=BACTERIA_SPECIFY`,";",simplify = T)) %in% c(NA,NULL,"NA","NULL","SARS-CoV-2","Unk","NO"), na.rm = T)
        ){
            FALSE
        } else {TRUE}
        
    }
    
    processTime <- function(x){
        
        if (!is.na(x)){
            as.double(str_split(x, ";",simplify = T)[1])
        } else {
            NA
        }
        
    }
    
    
    forOxford <- function(selection,
                          hasConsent,
                          hadRNASeq,
                          samplesAvailable,
                          PAX_TUBE_TP2,
                          PAXProcessTime,
                          ...){
        
        if(!hasConsent){
            "No Consent"
        } else if(hadRNASeq){
            "Already Sequenced"
        } else if(PAX_TUBE_TP2 %in% "YES"){
            "Has TP2 sample"
        } else{
            
            if(selection %in% "possible MisC"){
                "?"
            } else if (selection %in% c("Full Mis-C Criteria","MisC with Co-Infection","Uncomplicated Covid","Atypical Covid")){
                if(is.na(samplesAvailable)){
                    "No Sample Data"
                } else if(samplesAvailable %in% "All") {
                    "1"
                } else if(samplesAvailable %in% c("No EDTA","No Serum")){
                    "2"
                } else if(samplesAvailable %in% "Only PAX"){
                    "3"
                } else {"No PAX"}
                
            } else{""}
            
        }
        
    }
    
    immunoDateTime <- function(TREATMENT,
                               TREATMENT_NAME,
                               DATE_TIME_INVESTIGATIONS.1,
                               ...){
        
        if(grepl("YES",TREATMENT) & 
           !is.na(TREATMENT_NAME) &
           !is.na(DATE_TIME_INVESTIGATIONS.1)){
            treatmentStarted <- which(str_split(TREATMENT,";",simplify = T)[1,] %in% "YES")
            paste((str_split(DATE_TIME_INVESTIGATIONS.1,";",simplify = T)[,c(treatmentStarted+1,treatmentStarted)]), collapse = " ")
        } else {
            NA_character_
        }
        
    }
    
    
    paxtoImuno <- function(TREATMENT,
                           TREATMENT_NAME,
                           DATE_TIME_INVESTIGATIONS.1,
                           PAX_DATE_TIME,
                           ...){
        
        if(grepl("YES",TREATMENT) & 
           grepl("STEROID|IMMUNOGLOBULIN|MONOCLONAL_AB",TREATMENT_NAME) & 
           (!is.na(PAX_DATE_TIME)) & (!is.na(DATE_TIME_INVESTIGATIONS.1)) & 
           (!is.na(TREATMENT_NAME)) & 
           (!is.na(TREATMENT))){
            
            treatmentStarted <- 2*(which(str_split(TREATMENT,";",simplify = T)[1,] %in% "YES"))
            
            Ix <- str_split(DATE_TIME_INVESTIGATIONS.1,";",simplify = T)[1,]
            Ix<- Ix[!Ix %in% c(NA,NULL,"NA","NULL")]
            
            if(length(Ix) >= treatmentStarted){
                
                dateTreatment <- as.POSIXct(paste((Ix[c(treatmentStarted-1,treatmentStarted)]), collapse = " "))
                
            } else {
                
                dateTreatment <- as.POSIXct(paste((Ix[c(1,2)]), collapse = " "))
                
            }
            
            
            as.numeric(difftime(dateTreatment, as.POSIXct(paste(str_split(PAX_DATE_TIME,";",simplify = T)[,1:2], collapse=" ")), units = "hours"))
            
        } else {NA_real_}
        
    }
    
    serumtoImuno <- function(TREATMENT,
                             TREATMENT_NAME,
                             DATE_TIME_INVESTIGATIONS.1,
                             SERUM_DATE_TIME,
                             ...){
        SERUM_DATE_TIME <- gsub("NULL;","",SERUM_DATE_TIME)
        if(grepl("YES",TREATMENT) & 
           grepl("STEROID|IMMUNOGLOBULIN|MONOCLONAL_AB",TREATMENT_NAME) & 
           (!is.na(SERUM_DATE_TIME)) & (!is.na(DATE_TIME_INVESTIGATIONS.1)) & 
           (!is.na(TREATMENT_NAME)) & 
           (!is.na(TREATMENT))){
            
            treatmentStarted <- 2*(which(str_split(TREATMENT,";",simplify = T)[1,] %in% "YES"))
            
            Ix <- str_split(DATE_TIME_INVESTIGATIONS.1,";",simplify = T)[1,]
            Ix<- Ix[!Ix %in% c(NA,NULL,"NA","NULL")]
            
            if(length(Ix) >= treatmentStarted){
                
                dateTreatment <- as.POSIXct(paste((Ix[c(treatmentStarted-1,treatmentStarted)]), collapse = " "))
                
            } else {
                
                dateTreatment <- as.POSIXct(paste((Ix[c(1,2)]), collapse = " "))
                
            }
            
            
            as.numeric(difftime(dateTreatment, as.POSIXct(paste(str_split(SERUM_DATE_TIME,";",simplify = T)[,1:2], collapse=" ")), units = "hours"))
            
        } else {NA_real_}
        
    }
    
    edtatoImuno <- function(TREATMENT,
                            TREATMENT_NAME,
                            DATE_TIME_INVESTIGATIONS.1,
                            EDTA_DATE_TIME,
                            ...){
        EDTA_DATE_TIME <- gsub("NULL;","",EDTA_DATE_TIME)
        
        if(grepl("YES",TREATMENT) & 
           grepl("STEROID|IMMUNOGLOBULIN|MONOCLONAL_AB",TREATMENT_NAME) & 
           (!is.na(EDTA_DATE_TIME)) & (!is.na(DATE_TIME_INVESTIGATIONS.1)) & 
           (!is.na(TREATMENT_NAME)) & 
           (!is.na(TREATMENT))){
            
            treatmentStarted <- 2*(which(str_split(TREATMENT,";",simplify = T)[1,] %in% "YES"))
            
            Ix <- str_split(DATE_TIME_INVESTIGATIONS.1,";",simplify = T)[1,]
            Ix<- Ix[!Ix %in% c(NA,NULL,"NA","NULL")]
            
            if(length(Ix) >= treatmentStarted){
                
                dateTreatment <- as.POSIXct(paste((Ix[c(treatmentStarted-1,treatmentStarted)]), collapse = " "))
                
            } else {
                
                dateTreatment <- as.POSIXct(paste((Ix[c(1,2)]), collapse = " "))
                
            }
            
            
            as.numeric(difftime(dateTreatment, as.POSIXct(paste(str_split(EDTA_DATE_TIME,";",simplify = T)[,1:2], collapse=" ")), units = "hours"))
            
        } else {NA_real_}
        
    }
    
    numberOfSamples <- function(PAX_TUBE_TP1,
                                PAX_TUBE_TP2,
                                PAX_TUBE_DIS,...){
        
        sum(c(PAX_TUBE_TP1,PAX_TUBE_TP2,PAX_TUBE_DIS) %in% "YES")
        
    }
    
    
    
    
    makeDF <- function(diamonds){
        
        diamonds %>% mutate(
   
                #calcuate age ata symptom onset, hospital admission or base on todays date
                age = case_when(
                    is.na(as.Date(DATE_OF_BIRTH)) ~ NA_real_,
                    !is.na(as.Date(DATE_SYMPTOM_ONSET)) ~ as.numeric(as.Date(DATE_SYMPTOM_ONSET) - as.Date(DATE_OF_BIRTH))/365,
                    !is.na(as.Date(DATETIME_FIRST_HOSPITAL)) ~ as.numeric(as.Date(DATETIME_FIRST_HOSPITAL) - as.Date(DATE_OF_BIRTH))/365,
                    TRUE ~ as.numeric(Sys.Date() - as.Date(DATE_OF_BIRTH))/365
                ),
                
                #Apply positive and negative covid functions above
                positiveCovidTests = pmap_chr(.,positiveCovidTests),
                negativeCovidTests = pmap_chr(.,negativeCovidTests),
                
                
                InflammatoryPatient = if_else(
                    FINAL_PHENOTYPE_DIAGNOSIS %in% "INFLAMATORY SYNDROM" | SECONDARY_PHENOTYPE %in% "Inflammatory" | !is.na(INFLAMMATORY),
                    TRUE,
                    FALSE
                ),
                
                anyCovidPos = if_else(
                    PREVIOUS_HISTORY_COVID19 %in% "Yes" | PREVIOUS_ADMISSION_COVID19 %in% "Yes" | !is.na(positiveCovidTests),
                    TRUE,
                    FALSE
                ),
                
                covidPCRPos = if_else(
                    grepl("PCR|ANTIGEN",positiveCovidTests),
                    TRUE,
                    FALSE
                ),
                
                anyfeaturesofIllness = pmap_lgl(.,anyFeatures),
                
                paediatric = if_else(
                    age<19,
                    TRUE,
                    FALSE
                ),
                
                feverLength = pmap_dbl(.,feverLength),
                
                raisedInflam = if_else(
                    MAXIMUM_CRP > CRP | any(as.numeric(gsub(".*=","",str_split(diamonds$`TIME_POINT_17=PCT`[942],";", simplify = T))) > PCT),
                    TRUE,
                    FALSE
                ),
                
                otherOrgs = pmap_lgl(., otherOrgs),
                
                misCFeatures = pmap_dbl(.,misCFeatures),
                
                KDFeatures = pmap_dbl(., KDcriteria),
                
                maxZscore = pmap_dbl(., maxZscore)
                
            ) %>%
            
            mutate(
                
                fullMisC = if_else(
                    InflammatoryPatient & (anyCovidPos|INFLAMMATORY %in% "COVID-RELATED INFLAMMATION") & paediatric & feverLength>=3 & raisedInflam & (!otherOrgs) & misCFeatures>=2,
                    TRUE,
                    FALSE
                ),
                
                MiscCwithCoInfection = if_else(
                    InflammatoryPatient & (anyCovidPos|INFLAMMATORY %in% "COVID-RELATED INFLAMMATION") & paediatric & feverLength>=3 & raisedInflam & otherOrgs & misCFeatures>=2,
                    TRUE,
                    FALSE
                ),
                
                OtherCovidInflam = if_else(
                    InflammatoryPatient & (anyCovidPos|INFLAMMATORY %in% "COVID-RELATED INFLAMMATION") & paediatric & !(feverLength>=3 & raisedInflam & otherOrgs & misCFeatures>=2),
                    TRUE,
                    FALSE
                ),
                
                NonCovidInflammation = if_else(
                    InflammatoryPatient & (!INFLAMMATORY %in% "COVID-RELATED INFLAMMATION") & paediatric & !anyCovidPos,
                    TRUE,
                    FALSE
                ),
                
                incidentalCovid = if_else(
                    covidPCRPos & !anyfeaturesofIllness & paediatric,
                    TRUE,
                    FALSE
                ),
                
                covidCoinfection = if_else(
                    covidPCRPos & anyfeaturesofIllness & otherOrgs & paediatric,
                    TRUE,
                    FALSE
                ),
                
                uncomplicatedCovid = if_else(
                    covidPCRPos & anyfeaturesofIllness & paediatric & (!otherOrgs) & (!InflammatoryPatient) & grepl("COIVD19",PATHOGEN_SYNDROMES) & FINAL_PHENOTYPE_DIAGNOSIS %in% c("VIRAL SYNDROME","DEFINITE VIRAL"),
                    TRUE,
                    FALSE
                ),
                
                atypicalCovid = if_else(
                    covidPCRPos & paediatric & anyfeaturesofIllness & (!otherOrgs) & (!InflammatoryPatient) & !(grepl("COIVD19",PATHOGEN_SYNDROMES) & FINAL_PHENOTYPE_DIAGNOSIS %in% c("VIRAL SYNDROME","DEFINITE VIRAL")),
                    TRUE,
                    FALSE
                ),
                
                
                classicalKD = if_else(
                    feverLength >=4 & KDFeatures >=4,
                    TRUE,
                    FALSE
                ),
                
                atypicalKD = if_else(
                    (!is.na(maxZscore)) & maxZscore >2.5,
                    TRUE,
                    FALSE)
                
            ) %>% filter(SITE_CODE %in% c(1101:1199))
    }
    #### Make DF ####
   
    
    selectionsDF <- makeDF(diamonds)
```

## Number of Children on Database

```{r children, echo=F}
sum(selectionsDF$paediatric, na.rm = T)
```

## Number meeting Full WHO MisC criteria
```{r misC, echo=F}
sum(selectionsDF$fullMisC, na.rm = T)
```


## Number with any positive Covid Test (incl bothe antigent, antibody)

```{r anyCovid, echo=F}
sum(selectionsDF$anyCovidPos, na.rm = T)
```

## Number  PCR +ve for Covid
```{r PCR, echo=F}
sum(selectionsDF$covidPCRPos, na.rm = T)
    ```
   
   
## Number  Meeting Classical and Atypical KD criteria
```{r KD, echo=F}
nrow(selectionsDF %>% filter(classicalKD | atypicalKD))
    ```
    
    
## Number  Meeting Classical and Atypical KD criteria that do not meet MisC criteria
```{r KDnotMisc, echo=F}
nrow(selectionsDF %>% filter((classicalKD | atypicalKD) & !fullMisC))
    ```
    